name: auto-update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  mi_tv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: npm install
      - name: Run EPG Grabber
        run: npx epg-grabber --config=sites/mi.tv.config.js
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: '["./lib/guide.xml"]'
          author_name: "Silas Alves dos Santos"
          author_email: "sialsan@hotmail.com"
          branch: main
          message: "Github actions updated guide"
          push: "origin main --force"
