name: auto-update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  mi_tv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: npm install
      - name: Run EPG Grabber
        run: npx epg-grabber --config=sites/mi.tv.config.js
      - name: Deploy to GitHub Pages
        uses: mrcanelas/github-pages-deploy-action@4.1.0